### ISSUE TITLE
Add support RBAC, ALM and License key in Helm chart

### ISSUE THREAD

**Issue by giovren** [ICTU/sonar#86]
# Add the option in values.yml to specify usergroups and permissions in SonarQube

Example values.yml:
```
rbac:
  enabled: true
  all_global_permissions: ["admin", "profileadmin", "gateadmin", "scan", "provisioning"]
  all_project_permissions: ["admin", "codeviewer", "issueadmin", "securityhotspotadmin", "scan", "user"]
  user_groups:
    - name: "test-administrators"
      global_permissions: ["admin", "profileadmin", "gateadmin", "scan", "provisioning"]
      project_permissions: ["user", "codeviewer", "scan", "admin", "issueadmin", "securityhotspotadmin"]
    - name: "test-developers"
      global_permissions: ["gateadmin", "scan"]
      project_permissions: ["user", "codeviewer"]
```

This should:
* create user groups `test-administrators` and `test-developers`
* User group `test-administrators` should have global permissions `"admin", "profileadmin", "gateadmin", "scan", "provisioning"` and project permissions `"user", "codeviewer", "scan", "admin", "issueadmin", "securityhotspotadmin"`
*  User group `test-developers` should have global permissions `"gateadmin", "scan"` and project_permissions `"user", "codeviewer"`
* any global permissions in `all_global_permissions` that are not listed in the user group global permissions should be removed from the user group
* any project permissions in `all_project_permissions` that are not listed in the user group project permissions should be removed from the user group

# Add the option in values.yml to specify license key to activate Developer Edition

Example values.yml:

```
license:
  key:
```

This should:
* Install the license key specified if Developer Edition of SonarQube is deployed

# Add the option in values.yml to configure ALM integration with a given GitLab instance

Example values.yml:

```
alm:
  gitlab:
    key: mygitlab
    personalAccessToken: 1234
    url:  https://mygitlab/api/v4
```

This should:
* Create a integration called `mygitlab` and configure the specified url and PAT
